PcForge/PcForge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('paypal/', include('paypal.standard.ipn.urls')),


    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PcForge/app/urls.py
from django.urls import path
from .views import home, productos,contacto, agregar_productos, listar_productos, \
      modificar_productos, eliminar_productos, registro, exit, registro_admin, detalle_producto,\
      lista_categorias, productos_por_categoria,agregar_al_carrito_armar_pc,\
      ver_carrito_armar_pc, ver_carrito, agregar_al_carrito, quitar_del_carrito, ver_wishlist, \
        agregar_a_wishlist, quitar_de_wishlist,procesar_pago,procesar_pago_carrito, iniciar_pago,\
        paypal_return,paypal_cancel,iniciar_pago_componentes, paypal_return_componentes, \
        paypal_cancel_componentes, ver_perfil,modificar_perfil, ver_pedidos, detalle_pedido,\
        ver_pedidos_global, detalle_pedido_global, agregar_version, lista_versiones, editar_version,\
        guardar_edicion_version,agregar_al_carrito_componentes, desactivar_producto, activar_producto, crear_tarro, lista_tarros, detalle_tarro
      
urlpatterns = [
    path('',home, name="home" ),
    path('productos/',productos, name="productos" ),
    path('contacto/',contacto, name="contacto" ),
    path('agregar-productos/',agregar_productos, name="agregar_productos" ),
    path('listar-productos/',listar_productos, name="listar_productos" ),
    path('modificar-productos/<id>/',modificar_productos, name="modificar_productos" ),
    path('eliminar-productos/<id>/',eliminar_productos, name="eliminar_productos" ),
    path('registro/',registro, name="registro" ),
    path('registro_admin/',registro_admin, name="registro_admin" ),
    path('Logout/', exit, name="exit"),
    path('productos/detalle/<int:producto_id>/', detalle_producto, name='detalle_producto'),
     path('categorias/', lista_categorias, name='lista_categorias'),
    path('productos_por_categoria/<int:categoria_id>/', productos_por_categoria, name='productos_por_categoria'),
    
    path('agregar_al_carrito_armar_pc/<int:producto_id>/', agregar_al_carrito_armar_pc, name='agregar_al_carrito_armar_pc'),
    
    
    path('ver_carrito_armar_pc/', ver_carrito_armar_pc, name='ver_carrito_armar_pc'),
    path('ver-pedidos/', ver_pedidos, name='ver_pedidos'),
    path('detalle-pedido/<int:pedido_id>/', detalle_pedido, name='detalle_pedido'),

    

    path('ver-carrito/', ver_carrito, name='ver_carrito'),
    path('agregar-al-carrito/<int:producto_id>/', agregar_al_carrito, name='agregar_al_carrito'),
    

    path('quitar-del-carrito/<int:itemcarrito_id>/', quitar_del_carrito, name='quitar_del_carrito'),
    path('ver-wishlist/',ver_wishlist, name='ver_wishlist'),
    path('agregar-wishlist/<int:producto_id>/', agregar_a_wishlist, name='agregar_a_wishlist'),
    path('quitar-wishlist/<int:producto_id>/', quitar_de_wishlist, name='quitar_de_wishlist'),
    path('procesar_pago/', procesar_pago, name='procesar_pago'),
    path('procesar_pago_carrito/', procesar_pago_carrito, name='procesar_pago_carrito'),


    path('iniciar_pago/', iniciar_pago, name='iniciar_pago'),
    path('paypal-reverse/', paypal_return, name='paypal-return'),
    path('paypal-cancel/', paypal_cancel, name='paypal-cancel'),


    path('iniciar_pago_componentes/', iniciar_pago_componentes, name='iniciar_pago_componentes'),
    path('paypal-return-componentes/', paypal_return_componentes, name='paypal-return-componentes'),
    path('paypal-cancel-componentes/', paypal_cancel_componentes, name='paypal-cancel-componentes'),
    path('ver-perfil/', ver_perfil, name='ver_perfil'),

    path('modificar-perfil/', modificar_perfil, name='modificar_perfil'),
    path('ver-pedidos-global/', ver_pedidos_global, name='ver_pedidos_global'),

    path('detalle-pedido-global/<int:pedido_id>/',detalle_pedido_global, name='detalle_pedido_global'),
    path('agregar_version/', agregar_version, name='agregar_version'),
    path('lista_versiones/', lista_versiones, name='lista_versiones'),
    path('editar_version/<int:version_id>/', editar_version, name='editar_version'),
    path('guardar_edicion_version/<int:version_id>/', guardar_edicion_version, name='guardar_edicion_version'),
    path('agregar_al_carrito_componentes/', agregar_al_carrito_componentes, name='agregar_al_carrito_componentes'),
    path('desactivar-producto/<int:producto_id>/', desactivar_producto, name='desactivar_producto'),
    path('activar-producto/<int:producto_id>/', activar_producto, name='activar_producto'),
    path('crear_tarro/', crear_tarro, name='crear_tarro'),
    path('lista_tarros/', lista_tarros, name='lista_tarros'),
    path('detalle_tarro/<int:tarro_id>/', detalle_tarro, name='detalle_tarro'),
    

]

PcForge/app/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User



from django.db import models
from django.contrib.auth.models import User



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, blank=True)
    apellido = models.CharField(max_length=100, blank=True)
    direccion = models.CharField(max_length=255, blank=True)
    numero_telefono = models.CharField(max_length=15, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    genero = models.CharField(max_length=10, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], blank=True)
    imagen_perfil = models.ImageField(upload_to="perfil", null=True, blank=True)
    biografia = models.TextField(blank=True)

    def __str__(self):
        return f"Perfil de {self.user.username}"




class Marca(models.Model):
    nombre = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nombre


class Categoria(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

class Version(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre
    
class Tarro(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    descripcion = models.TextField(max_length=255)
    

class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    precio = models.IntegerField()
    nuevo = models.BooleanField()
    stock = models.IntegerField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField(null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to="productos", null=True, blank=True)
    version = models.ForeignKey(Version, on_delete=models.PROTECT)
    activo = models.BooleanField(default=True)  
    tarro = models.ForeignKey(Tarro, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre


    

opciones_consultas = [
[0, "Consulta"],
[1, "Reclamo"],
[2, "Sugerencia"],
[3, "Felicitaciones"],

]

class ListaDeseos(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField('Producto', related_name='wishlist')

    def __str__(self):
        return f'Wishlist de {self.usuario.username}'

class Contacto(models.Model):
    nombre = models.CharField(max_length=250)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre
    



class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='ItemCarrito')
    descuento =models.IntegerField(default=0)
    total = models.IntegerField(default=0)

    def calcular_total(self):
        return sum(item.subtotal() for item in self.itemcarrito_set.all())

    def actualizar_total(self):
        self.total = self.calcular_total()
        self.save()


    def limpiar_carrito(self):
        # Lógica para limpiar el carrito, si es necesario
        # Por ejemplo, puedes eliminar todos los elementos del carrito
        self.productos.clear()
        self.actualizar_total()

    def __str__(self):
        return f"Carrito de {self.usuario.username}"
class ItemCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.producto.precio * self.cantidad

    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre} en {self.carrito}"




from django.db import models
from .models import Producto

from django.db import models
from django.contrib.auth.models import User

from django.db import models
from django.contrib.auth.models import User

class CarritoArmarPC(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    placa_base = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_placa_base')
    procesador = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_procesador')
    ram = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_ram')
    tarjeta_grafica = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_tarjeta_grafica')
    disco = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_disco')
    fuente_poder = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_fuente_poder')
    gabinete = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_gabinete')
    disipador = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_disipador')
    descuento =models.IntegerField(default=0)
    equipo_armado = models.BooleanField(default=False)
    total = models.IntegerField(default=0)

    def calcular_total(self):
        total = sum(producto.precio for producto in self.obtener_productos_dict().values() if producto)
        self.total = total
        self.save()
        return total

    def obtener_productos_dict(self):
        return {
            'Placa Base': self.placa_base,
            'Procesador': self.procesador,
            'RAM': self.ram,
            'Disco': self.disco,
            'Tarjeta Gráfica': self.tarjeta_grafica,
            'Disipador': self.disipador,
            'Gabinete': self.gabinete,
            'Fuente de Poder': self.fuente_poder,
        }



    def limpiar_carrito(self):
        for field_name in self._meta.get_fields():
            if field_name.name.startswith('carrito_armar_pc_') and isinstance(getattr(self, field_name.name), Producto):
                # Eliminar la referencia ForeignKey
                setattr(self, field_name.name, None)

        # Establecer todos los campos en None
        self.placa_base = None
        self.procesador = None
        self.ram = None
        self.tarjeta_grafica = None
        self.disco = None
        self.fuente_poder = None
        self.gabinete = None
        self.disipador = None

        self.total = 0
        self.save()
    


class Boleta(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    valor_total = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Boleta ID {self.id} de {self.usuario.username}"

    

class DetalleBoleta(models.Model):
    boleta = models.ForeignKey(Boleta, on_delete=models.CASCADE, related_name='detalles_boleta')
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    precio_unitario = models.IntegerField()

    def calcular_subtotal(self):
        return self.cantidad * self.precio_unitario
    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre} en Boleta {self.boleta.id}"
    

from django.db import models
from django.contrib.auth.models import User

# models.py

from django.db import models
from django.contrib.auth.models import User

class Comentario(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    contenido = models.TextField()
    evaluacion = models.IntegerField(choices=[(i, i) for i in range(1, 6)])  # Del 1 al 5
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comentario de {self.cliente.username} en {self.producto.nombre}"



class Pedido(models.Model):
    ESTADOS_PEDIDO = [
        ('preparacion', 'En preparación'),
        ('ensamblaje', 'En Ensamblaje'),
        ('en_camino', 'En camino'),
        ('entregado', 'Entregado'),
        # Agrega más estados según sea necesario
    ]

    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    vendedor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='pedidos_vendedor')
    estado = models.CharField(max_length=20, choices=ESTADOS_PEDIDO, default='preparacion')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    boleta = models.ForeignKey(Boleta, on_delete=models.CASCADE)
    direccion_entrega = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"Pedido #{self.id} - {self.get_estado_display()}"
    

    def permitir_comentarios(self):
        # Lógica para determinar si se deben permitir comentarios basados en el estado del pedido
        return self.estado == 'entregado'


class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    def calcular_subtotal(self):
        return self.producto.precio * self.cantidad
    
    def __str__(self):
        return f"Detalle Pedido #{self.pedido.id}"

PcForge/app/templates/app/productos/agregar_productos.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2>Nuevo Producto</h2>
                    <hr>
                    <!-- Formulario de AdminLTE -->
                    <!DOCTYPE html>
                    <html lang="en">
                    <head>
                      <meta charset="utf-8">
                      <meta name="viewport" content="width=device-width, initial-scale=1">
                      <title>AdminLTE 3 | General Form Elements</title>

                      <!-- Google Font: Source Sans Pro -->
                      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
                      <!-- Font Awesome -->
                      <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
                      <!-- Theme style -->
                      <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.min.css' %}">
                    </head>
                    <body class="hold-transition sidebar-mini">
                    <div class="wrapper">
                      <!-- Contenido del formulario aquí -->
                      <form action="" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                          {{ form | crispy }}
                          <div class="d-flex justify-content-end">
                              <input type="reset" value="Cancelar" class="btn btn-warning">
                              &nbsp;
                              <input type="submit" value="Guardar" class="btn btn-primary">
                          </div>
                      </form>
                      <!-- Fin del contenido del formulario -->
                    </div>
                    <!-- jQuery -->
                    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
                    <!-- Bootstrap 4 -->
                    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
                    <!-- bs-custom-file-input -->
                    <script src="{% static 'adminlte/plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
                    <!-- AdminLTE App -->
                    <script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>
                    <!-- AdminLTE for demo purposes -->
                    <script src="{% static 'adminlte/js/demo.js' %}"></script>
                    <!-- Page specific script -->
                    <script>
                    $(function () {
                      bsCustomFileInput.init();
                    });
                    </script>
                    </body>
                    </html>
                    <!-- Fin del formulario de AdminLTE -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PcForge/app/templates/app/productos/detalle_producto.html
<!-- templates/detalle_producto.html -->
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block contenido %}
<div class="container mt-4">
    <div class="feature-box">
        <div class="card-body">
            <h1>Detalles del Producto</h1>

            <div class="row">
                <div class="col-md-6">
                    <img src="{{ producto.imagen.url }}" class="img-fluid" alt="{{ producto.nombre }}">
                </div>
                <div class="col-md-6">
                    <h2>{{ producto.nombre | title }}</h2>
                    <p class="price">Precio: ${{ producto.precio | intcomma }}</p>
                    <p>Marca: {{ producto.marca }}</p>
                    <p>¿Es nuevo? {% if producto.nuevo %}Si{% else %}No{% endif %}</p>
                    <p>Version: {{ producto.version }}</p>
                    <p>Stock disponible: {{ producto.stock }}</p>
                    <p>Categoría: {{ producto.categoria }}</p>
                    <p>Fecha de fabricación: {{ producto.fecha_fabricacion }}</p>

                    <h3>Descripción:</h3>
                    <p>{{ producto.descripcion }}</p>

                    <!-- Puedes agregar más detalles según tus necesidades -->

                    <!-- Formulario para agregar al carrito de Armar PC -->
                    <form method="post" action="{% url 'agregar_al_carrito' producto.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary" {% if not producto.activo %}disabled{% endif %}>
                            {% if not producto.activo %}Proximamente{% else %}Agregar al Carrito{% endif %}
                        </button>
                    </form>
                    <br>
                    <form method="post" action="{% url 'agregar_al_carrito_armar_pc' producto.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary" {% if not producto.activo %}disabled{% endif %}>
                            {% if not producto.activo %}Proximamente{% else %}Arma Tu PC{% endif %}
                        </button>
                    </form>

                    <br>
                    <form method="post" action="{% url 'agregar_a_wishlist' producto.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary" {% if not producto.activo %}disabled{% endif %}>
                            {% if not producto.activo %}Proximamente{% else %}Agregar a Wishlist{% endif %}
                        </button>
                    </form>
                    <!-- Repite el formulario para cada categoría según tus necesidades -->

                </div>
            </div>

        </div>
    </div>

    <div class="mt-4">
        <div class="card mb-3">
            <div class="card-body">
                <h3 class="card-title">Comentarios</h3>
                {% for comentario in producto.comentario_set.all %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <p class="card-text"><strong>{{ comentario.cliente.username }}</strong> - {{ comentario.fecha_creacion }}</p>
                            <p class="card-text">Evaluación: {{ comentario.evaluacion }}/5</p>
                            <p class="card-text">{{ comentario.contenido }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="card mb-3">
            <div class="card-body">
                <h3 class="card-title">Deja un Comentario</h3>
                <form method="post" action="{% url 'detalle_producto' producto.id %}">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-primary">Enviar Comentario</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

PcForge/app/templates/app/productos/lista_categorias.html
{% extends 'app/base.html' %}

{% block contenido %}
    <h1>Seleccione una categoría:</h1>
    <ul>
        {% for categoria in categorias %}
            <li><a href="{% url 'productos_por_categoria' categoria.categoria %}">{{ categoria.categoria }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

PcForge/app/templates/app/productos/listar_productos.html
{% extends 'app/base.html' %}

{% load crispy_forms_tags %}
{% load humanize %}
{% block contenido %}
<div class="container lis_productos">
    <br>
    <div class="card">
        <div class="card-body">
            <h1>Listado de productos</h1>

            <table class="table table-striped table-hover table-responsive-sm">

                <th>Nombre</th>
                <th>Precio</th>
                <th>Marca</th>
                <th>¿Es nuevo?</th>
                <th>Opciones</th>

                {% for p in productos %}

                <tr>

                    <td>{{ p.nombre | title }}</td>
                    <td class="price">${{ p.precio | intcomma }}</td>
                    <td>{{ p.marca }}</td>
                    <td>
                        {% if p.nuevo %}
                            Si
                        {% else %}
                            No
                        {% endif %}
                    </td>
                    <td>
                        {% if perms.app.change_producto %}
                            <a href="#" onclick="desactivarActivarProducto({{ p.id }}, {{ p.activo|yesno:"true,false" }})" class="btn btn-warning">
                                {% if p.activo %}
                                    Desactivar
                                {% else %}
                                    Activar
                                {% endif %}
                            </a>
                        {% endif %}

                        &nbsp;
                        <a href="{% url 'modificar_productos' p.id %}" class="btn btn-primary">Editar</a>

                    </td>

                </tr>

                {% endfor %}

            </table>
            <hr>
            <div>

                {% include 'app/paginator.html' %}

            </div>

        </div>
    </div>

</div>

<script>
    function desactivarActivarProducto(id, activo) {
        Swal.fire({
            title: `¿Estás seguro de ${activo ? 'desactivar' : 'activar'} este producto?`,
            icon: 'question',
            showCancelButton: true,
            confirmButtonColor: '#dc3545',
            confirmButtonText: `Sí, ${activo ? 'Desactivar' : 'Activar'}`,
            cancelButtonText: 'No, Cancelar',
            reverseButtons: true,
        }).then((result) => {
            if (result.isConfirmed) {
                // Llamar a la función para desactivar/activar producto
                const url = activo ? `/desactivar-producto/${id}/` : `/activar-producto/${id}/`;
                fetch(url, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                }).then((response) => {
                    if (response.ok) {
                        // Recargar la página después de la operación exitosa
                        location.reload();
                    } else {
                        Swal.fire({
                            title: 'Error',
                            text: 'Hubo un error al procesar la solicitud.',
                            icon: 'error',
                        });
                    }
                });
            }
        });
    }
</script>

{% endblock %}

PcForge/app/templates/app/productos/modificar_productos.html
{% extends 'app/base.html' %}

{% load crispy_forms_tags %}

{% block contenido %}
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2>Modificar Producto</h2>
                    <hr>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-warning">
                            &nbsp;
                            <input type="submit" value="Editar" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PcForge/app/templates/app/productos/productos_por_categoria.html
<!-- productos_por_categoria.html -->

{% extends 'app/base.html' %}
{% block contenido %}
{% load crispy_forms_tags %}
<div class="container mt-5">
  <h2 class="text-center mb-4">Productos de la categoría {{ categoria_seleccionada.nombre }}</h2>

  <form method="get" action="{% url 'productos_por_categoria' categoria_id %}">
    {{ form | crispy }}
    <button type="submit" class="btn btn-secondary btn-sm">Filtrar</button>
</form>


  {% if productos %}
    <div class="row">
      {% for producto in productos %}
        <div class="col-md-4">
          <div class="feature-box">
            {% if producto.imagen %}
              <img src="{{ producto.imagen.url }}" class="img-fluid" alt="{{ producto.nombre }}" style="height: 200px;">
            {% else %}
              <p>No hay imagen disponible</p>
            {% endif %}
            <h3>{{ producto.nombre }}</h3>
            <p class="price">${{ producto.precio }}</p>
            <p>{{ producto.descripcion |truncatechars:100 }}</p>
            <a href="{% url 'detalle_producto' producto.id %}" class="btn btn-primary">Ver detalles</a>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p class="text-center">No hay productos en esta categoría.</p>
  {% endif %}

  <div class="text-center mt-3">
    <a href="{% url 'home' %}" class="btn btn-primary">Volver al inicio</a>
  </div>
</div>

{% endblock %}

PcForge/app/templates/app/productos/ver_wishlist.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block contenido %}

<div class="container wishlist">
    <br>
    <div class="card">
      <div class="card-body">
  <h2 class="text-center mb-4">Lista de Deseos</h2>

  {% if wishlist.productos.all %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Producto</th>
          <th scope="col">Acciones</th>
          <th scope="col">Precio</th>
        </tr>
      </thead>
      <tbody>
        {% for producto in wishlist.productos.all %}
          <tr>
            <td>{{ producto.nombre }}</td>
            <td>
              <a href="{% url 'quitar_de_wishlist' producto.id %}" class="btn btn-danger btn-sm">Quitar</a>
            </td>
            <td>${{ producto.precio | intcomma }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="text-center">Tu lista de deseos está vacía.</p>
  {% endif %}
  <tr>
    <td>
    <a href="{% url 'productos' %}" class="btn btn-primary">Seguir agregando</a>
    <td>
    <td>
    <a href="{% url 'home' %}" class="btn btn-primary">Volver al inicio</a>
    </td>
</div>
</div>
</div>

{% endblock %}