PcForge/PcForge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('paypal/', include('paypal.standard.ipn.urls')),


    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PcForge/app/urls.py
from django.urls import path
from .views import home, productos,contacto, agregar_productos, listar_productos, \
      modificar_productos, eliminar_productos, registro, exit, registro_admin, detalle_producto,\
      lista_categorias, productos_por_categoria,agregar_al_carrito_armar_pc,\
      ver_carrito_armar_pc, ver_carrito, agregar_al_carrito, quitar_del_carrito, ver_wishlist, \
        agregar_a_wishlist, quitar_de_wishlist,procesar_pago,procesar_pago_carrito, iniciar_pago,\
        paypal_return,paypal_cancel,iniciar_pago_componentes, paypal_return_componentes, \
        paypal_cancel_componentes, ver_perfil,modificar_perfil, ver_pedidos, detalle_pedido,\
        ver_pedidos_global, detalle_pedido_global, agregar_version, lista_versiones, editar_version,\
        guardar_edicion_version,agregar_al_carrito_componentes, desactivar_producto, activar_producto, crear_tarro, lista_tarros, detalle_tarro
      
urlpatterns = [
    path('',home, name="home" ),
    path('productos/',productos, name="productos" ),
    path('contacto/',contacto, name="contacto" ),
    path('agregar-productos/',agregar_productos, name="agregar_productos" ),
    path('listar-productos/',listar_productos, name="listar_productos" ),
    path('modificar-productos/<id>/',modificar_productos, name="modificar_productos" ),
    path('eliminar-productos/<id>/',eliminar_productos, name="eliminar_productos" ),
    path('registro/',registro, name="registro" ),
    path('registro_admin/',registro_admin, name="registro_admin" ),
    path('Logout/', exit, name="exit"),
    path('productos/detalle/<int:producto_id>/', detalle_producto, name='detalle_producto'),
     path('categorias/', lista_categorias, name='lista_categorias'),
    path('productos_por_categoria/<int:categoria_id>/', productos_por_categoria, name='productos_por_categoria'),
    
    path('agregar_al_carrito_armar_pc/<int:producto_id>/', agregar_al_carrito_armar_pc, name='agregar_al_carrito_armar_pc'),
    
    
    path('ver_carrito_armar_pc/', ver_carrito_armar_pc, name='ver_carrito_armar_pc'),
    path('ver-pedidos/', ver_pedidos, name='ver_pedidos'),
    path('detalle-pedido/<int:pedido_id>/', detalle_pedido, name='detalle_pedido'),

    

    path('ver-carrito/', ver_carrito, name='ver_carrito'),
    path('agregar-al-carrito/<int:producto_id>/', agregar_al_carrito, name='agregar_al_carrito'),
    

    path('quitar-del-carrito/<int:itemcarrito_id>/', quitar_del_carrito, name='quitar_del_carrito'),
    path('ver-wishlist/',ver_wishlist, name='ver_wishlist'),
    path('agregar-wishlist/<int:producto_id>/', agregar_a_wishlist, name='agregar_a_wishlist'),
    path('quitar-wishlist/<int:producto_id>/', quitar_de_wishlist, name='quitar_de_wishlist'),
    path('procesar_pago/', procesar_pago, name='procesar_pago'),
    path('procesar_pago_carrito/', procesar_pago_carrito, name='procesar_pago_carrito'),


    path('iniciar_pago/', iniciar_pago, name='iniciar_pago'),
    path('paypal-reverse/', paypal_return, name='paypal-return'),
    path('paypal-cancel/', paypal_cancel, name='paypal-cancel'),


    path('iniciar_pago_componentes/', iniciar_pago_componentes, name='iniciar_pago_componentes'),
    path('paypal-return-componentes/', paypal_return_componentes, name='paypal-return-componentes'),
    path('paypal-cancel-componentes/', paypal_cancel_componentes, name='paypal-cancel-componentes'),
    path('ver-perfil/', ver_perfil, name='ver_perfil'),

    path('modificar-perfil/', modificar_perfil, name='modificar_perfil'),
    path('ver-pedidos-global/', ver_pedidos_global, name='ver_pedidos_global'),

    path('detalle-pedido-global/<int:pedido_id>/',detalle_pedido_global, name='detalle_pedido_global'),
    path('agregar_version/', agregar_version, name='agregar_version'),
    path('lista_versiones/', lista_versiones, name='lista_versiones'),
    path('editar_version/<int:version_id>/', editar_version, name='editar_version'),
    path('guardar_edicion_version/<int:version_id>/', guardar_edicion_version, name='guardar_edicion_version'),
    path('agregar_al_carrito_componentes/', agregar_al_carrito_componentes, name='agregar_al_carrito_componentes'),
    path('desactivar-producto/<int:producto_id>/', desactivar_producto, name='desactivar_producto'),
    path('activar-producto/<int:producto_id>/', activar_producto, name='activar_producto'),
    path('crear_tarro/', crear_tarro, name='crear_tarro'),
    path('lista_tarros/', lista_tarros, name='lista_tarros'),
    path('detalle_tarro/<int:tarro_id>/', detalle_tarro, name='detalle_tarro'),
    

]

PcForge/app/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User



from django.db import models
from django.contrib.auth.models import User



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, blank=True)
    apellido = models.CharField(max_length=100, blank=True)
    direccion = models.CharField(max_length=255, blank=True)
    numero_telefono = models.CharField(max_length=15, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    genero = models.CharField(max_length=10, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], blank=True)
    imagen_perfil = models.ImageField(upload_to="perfil", null=True, blank=True)
    biografia = models.TextField(blank=True)

    def __str__(self):
        return f"Perfil de {self.user.username}"




class Marca(models.Model):
    nombre = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nombre


class Categoria(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

class Version(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre
    
class Tarro(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    descripcion = models.TextField(max_length=255)
    

class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    precio = models.IntegerField()
    nuevo = models.BooleanField()
    stock = models.IntegerField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField(null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to="productos", null=True, blank=True)
    version = models.ForeignKey(Version, on_delete=models.PROTECT)
    activo = models.BooleanField(default=True)  
    tarro = models.ForeignKey(Tarro, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre


    

opciones_consultas = [
[0, "Consulta"],
[1, "Reclamo"],
[2, "Sugerencia"],
[3, "Felicitaciones"],

]

class ListaDeseos(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField('Producto', related_name='wishlist')

    def __str__(self):
        return f'Wishlist de {self.usuario.username}'

class Contacto(models.Model):
    nombre = models.CharField(max_length=250)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre
    



class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='ItemCarrito')
    descuento =models.IntegerField(default=0)
    total = models.IntegerField(default=0)

    def calcular_total(self):
        return sum(item.subtotal() for item in self.itemcarrito_set.all())

    def actualizar_total(self):
        self.total = self.calcular_total()
        self.save()


    def limpiar_carrito(self):
        # Lógica para limpiar el carrito, si es necesario
        # Por ejemplo, puedes eliminar todos los elementos del carrito
        self.productos.clear()
        self.actualizar_total()

    def __str__(self):
        return f"Carrito de {self.usuario.username}"
class ItemCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.producto.precio * self.cantidad

    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre} en {self.carrito}"




from django.db import models
from .models import Producto

from django.db import models
from django.contrib.auth.models import User

from django.db import models
from django.contrib.auth.models import User

class CarritoArmarPC(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    placa_base = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_placa_base')
    procesador = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_procesador')
    ram = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_ram')
    tarjeta_grafica = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_tarjeta_grafica')
    disco = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_disco')
    fuente_poder = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_fuente_poder')
    gabinete = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_gabinete')
    disipador = models.ForeignKey('Producto', on_delete=models.SET_NULL, null=True, blank=True, related_name='carrito_armar_pc_disipador')
    descuento =models.IntegerField(default=0)
    equipo_armado = models.BooleanField(default=False)
    total = models.IntegerField(default=0)

    def calcular_total(self):
        total = sum(producto.precio for producto in self.obtener_productos_dict().values() if producto)
        self.total = total
        self.save()
        return total

    def obtener_productos_dict(self):
        return {
            'Placa Base': self.placa_base,
            'Procesador': self.procesador,
            'RAM': self.ram,
            'Disco': self.disco,
            'Tarjeta Gráfica': self.tarjeta_grafica,
            'Disipador': self.disipador,
            'Gabinete': self.gabinete,
            'Fuente de Poder': self.fuente_poder,
        }



    def limpiar_carrito(self):
        for field_name in self._meta.get_fields():
            if field_name.name.startswith('carrito_armar_pc_') and isinstance(getattr(self, field_name.name), Producto):
                # Eliminar la referencia ForeignKey
                setattr(self, field_name.name, None)

        # Establecer todos los campos en None
        self.placa_base = None
        self.procesador = None
        self.ram = None
        self.tarjeta_grafica = None
        self.disco = None
        self.fuente_poder = None
        self.gabinete = None
        self.disipador = None

        self.total = 0
        self.save()
    


class Boleta(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    valor_total = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Boleta ID {self.id} de {self.usuario.username}"

    

class DetalleBoleta(models.Model):
    boleta = models.ForeignKey(Boleta, on_delete=models.CASCADE, related_name='detalles_boleta')
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    precio_unitario = models.IntegerField()

    def calcular_subtotal(self):
        return self.cantidad * self.precio_unitario
    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre} en Boleta {self.boleta.id}"
    

from django.db import models
from django.contrib.auth.models import User

# models.py

from django.db import models
from django.contrib.auth.models import User

class Comentario(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    contenido = models.TextField()
    evaluacion = models.IntegerField(choices=[(i, i) for i in range(1, 6)])  # Del 1 al 5
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comentario de {self.cliente.username} en {self.producto.nombre}"



class Pedido(models.Model):
    ESTADOS_PEDIDO = [
        ('preparacion', 'En preparación'),
        ('ensamblaje', 'En Ensamblaje'),
        ('en_camino', 'En camino'),
        ('entregado', 'Entregado'),
        # Agrega más estados según sea necesario
    ]

    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    vendedor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='pedidos_vendedor')
    estado = models.CharField(max_length=20, choices=ESTADOS_PEDIDO, default='preparacion')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    boleta = models.ForeignKey(Boleta, on_delete=models.CASCADE)
    direccion_entrega = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"Pedido #{self.id} - {self.get_estado_display()}"
    

    def permitir_comentarios(self):
        # Lógica para determinar si se deben permitir comentarios basados en el estado del pedido
        return self.estado == 'entregado'


class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    def calcular_subtotal(self):
        return self.producto.precio * self.cantidad
    
    def __str__(self):
        return f"Detalle Pedido #{self.pedido.id}"

PcForge/app/templates/app/agregar_al_carrito_componentes.html
<!-- templates/app/agregar_al_carrito_componentes.html -->
{% extends 'app/base.html' %}
{% block contenido %}
    <h2>Producto agregado al carrito de componentes</h2>
    <!-- Puedes agregar más contenido según tus necesidades -->
{% endblock %}

PcForge/app/templates/app/confirmacion_pago.html
<!--carrito armar pc-->

{% extends 'app/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block contenido %}
  <div class="container">
    <div class="card mt-4">
      <div class="card-body">
        <h2 class="card-title">Confirmación de Pago</h2>
        <p class="card-text">¡Gracias por tu compra! A continuación, te presentamos los detalles de tu boleta:</p>

        <div class="row">
          <div class="col-md-6">
            <p><strong>Boleta No:</strong> {{ boleta.id }}</p>
            <p><strong>Fecha de Compra:</strong> {{ boleta.fecha_creacion }}</p>
            <p><strong>Valor Total:</strong> ${{ boleta.valor_total | intcomma}}</p>
          </div>
        </div>

        <h3 class="mt-4">Detalles de la Boleta:</h3>
        <ul class="list-group">
          {% for detalle in boleta.detalles_boleta.all %}
            <li class="list-group-item">
              {{ detalle.producto.nombre }} - Cantidad: {{ detalle.cantidad }} - Subtotal: ${{ detalle.calcular_subtotal | intcomma}}
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

PcForge/app/templates/app/confirmacion_pago_carrito.html
{% extends 'app/base.html' %}

{% load crispy_forms_tags %}
{% load humanize %}

{% block contenido %}

  <div class="container">
    <h2>Confirmación de Pago</h2>
    <p>Gracias por tu compra. A continuación, te presentamos los detalles de tu boleta:</p>

    <p><strong>Boleta No:</strong> {{ boleta.id }}</p>
    <p><strong>Fecha de Compra:</strong> {{ boleta.fecha_creacion }}</p>
    <p><strong>Descuento:</strong> {{ carrito.descuento }}</p>
    <p><strong>Valor Total:</strong> ${{ boleta.valor_total }}</p>

    <h3>Detalles de la Boleta:</h3>
    <ul>
      {% for detalle in boleta.detalles_boleta.all %}
        <li>{{ detalle.producto.nombre }} - Cantidad: {{ detalle.cantidad }} - Subtotal: ${{ detalle.calcular_subtotal }}</li>
      {% endfor %}
    </ul>

    <p><a href="{% url 'home' %}" class="btn btn-primary">Volver a la Tienda</a></p>
  </div>
{% endblock %}

PcForge/app/templates/app/crear_tarro.html
{% extends 'app/base.html' %}

{% block contenido %}
<div class="container crear_tarro">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="mb-4">Crear Tarro</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Crear Tarro</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

PcForge/app/templates/app/detalle_pedido.html
{% extends 'app/base.html' %}




{% block contenido %}
    <div class="container mt-4">
        <h2 class="mb-4">Detalle del Pedido #{{ pedido.id }}</h2>
        
        <div class="card">
            <div class="card-body">
                <p><strong>Estado:</strong> {{ pedido.get_estado_display }}</p>
                <p><strong>Fecha de Creación:</strong> {{ pedido.fecha_creacion }}</p>
                <p><strong>Dirección de Entrega:</strong> {{ pedido.direccion_entrega }}</p>
                
                <h3 class="mt-3">Productos y Detalles:</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Producto</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for detalle in pedido.detallepedido_set.all %}
                            <tr>
                                <td>{{ detalle.producto.nombre }}</td>
                                <td>{{ detalle.cantidad }}</td>
                               
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
         
                
                {# Puedes agregar más detalles según sea necesario #}
                
                <a href="{% url 'ver_pedidos' %}" class="btn btn-primary">Volver a la lista de pedidos</a>
            </div>
        </div>
    </div>
{% endblock %}

PcForge/app/templates/app/detalle_pedido_global.html
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block contenido %}
    <div class="container mt-4">
        <h2 class="mb-4">Detalle del Pedido #{{ pedido.id }}</h2>
        
        <div class="card">
            <div class="card-body">
                <p><strong>Estado:</strong> {{ pedido.get_estado_display }}</p>
                <p><strong>Fecha de Creación:</strong> {{ pedido.fecha_creacion }}</p>
                <p><strong>Dirección de Entrega:</strong> {{ pedido.direccion_entrega }}</p>
                <p><strong>Cliente:</strong> {{ pedido.cliente.username }} </p>
                
                <h3 class="mt-3">Productos y Detalles:</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Producto</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for detalle in pedido.detallepedido_set.all %}
                            <tr>
                                <td>{{ detalle.producto.nombre }}</td>
                                <td>{{ detalle.cantidad }}</td>
                               
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
               <div class="text-center">
                    <form method="post" action="{% url 'detalle_pedido_global' pedido.id %}">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-warning">Actualizar</button>
                    
                  </form>
                  <br>
 
                <a href="{% url 'ver_pedidos' %}" class="btn btn-primary">Volver</a>

            </div>
            </div>
        </div>
    </div>
{% endblock %}

PcForge/app/templates/app/detalle_tarro.html
{% extends 'app/base.html' %}

{% block contenido %}
<div class="container detalle_tarro">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Detalles del Tarro {{ tarro.id }}</h2>

            <div class="card-text">
                <p class="mb-1"><strong>Usuario:</strong> {{ tarro.usuario.username }}</p>
                <p class="mb-1"><strong>Fecha de Creación:</strong> {{ tarro.fecha_creacion }}</p>
                <!-- Puedes agregar más detalles según tus necesidades -->
            </div>
            
            <a href="{% url 'lista_tarros' %}" class="btn btn-primary mt-3">Volver al Listado de Tarros</a>
        </div>
    </div>
</div>
{% endblock %}

PcForge/app/templates/app/iniciar_pago.html
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block contenido %}
    <div class="container">
        <br>
        <div class="card">
            <div class="card-body">
                <h1>Confirmar Pago</h1>
                <ul class="list-group">
                    {% for categoria, producto in productos_dict.items %}
                        <li class="list-group-item">
                            <strong>Producto:</strong> {{ producto.nombre }}<br>
                            <strong>Precio:</strong> ${{ producto.precio | intcomma }}<br>
                            <!-- Agrega más detalles según sea necesario -->
                        </li>
                    {% endfor %}
                    <li class="list-group-item">
                        <strong>Total:</strong> ${{ total_carrito | intcomma }}<br>
                        <!-- Mostrar el total con IVA -->
                        <strong>Total con IVA:</strong> ${{ total_con_iva | floatformat:2 }}</p>
                        
                        
                        <!-- Agrega más detalles según sea necesario -->
                    </li>
                </ul>
                
                <br>

                <div class="text-center">
                    <button class="btn btn-warning btn-sm">{{ form.render }}</button>
                    <a href="{% url 'paypal-cancel' %}" class="btn btn-danger">Cancelar Pago</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PcForge/app/templates/app/lista_tarros.html
{% extends 'app/base.html' %}

{% block contenido %}
<div class="container lista_tarros">
    <h1 class="mb-4">Listado de Tarros</h1>
    <div class="list-group">
        {% for tarro in tarros %}
            <div class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ tarro.id }}</h5>
                    <small>{{ tarro.fecha_creacion }}</small>
                </div>
                <p class="mb-1">Usuario: {{ tarro.usuario.username }}</p>
                <a href="{% url 'detalle_tarro' tarro.id %}" class="btn btn-primary btn-sm">Ver Detalles</a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

PcForge/app/templates/app/modificar_perfil.html
<!-- modificar_perfil.html -->

{% extends 'app/base.html' %}
{% load crispy_forms_tags %}

{% block contenido %}
    <div class="container modificar_perfil">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Modificar Perfil</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-12">
                                    {{ formulario.nombre|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    {{ formulario.apellido|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    {{ formulario.numero_telefono|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    {{ formulario.fecha_nacimiento|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    {{ formulario.direccion|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-12">
                                    {{ formulario.genero|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    {{ formulario.imagen_perfil|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    {{ formulario.biografia|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                                    <a href="{% url 'ver_perfil' %}" class="btn btn-secondary ml-2">Cancelar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

PcForge/app/templates/app/productos.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block contenido %}
<div class="container main-content">
    <div class="row">
        <div class="col-md-12 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <form method="get" action="{% url 'productos' %}">
                        {{ form | crispy }}
                        <button class="btn btn-secondary btn-sm" type="submit">Buscar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for p in productos %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{% if p.imagen %}{{ p.imagen.url }}{% else %}{% static 'app/placeholder.jpg' %}{% endif %}" class="card-img-top img-fluid producto-imagen" alt="{{ p.nombre }}">
                <div class="card-body">
                    <h5 class="card-title">{{ p.nombre | title | truncatechars:40 }}</h5>
                    <p class="card-text">{{ p.marca }}</p>
                    <p class="card-text price">${{ p.precio | intcomma }}</p>
                    <p class="card-text description">{{ p.descripcion | truncatechars:100 }}</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'detalle_producto' p.id %}" class="btn btn-primary btn-sm">Ver detalles</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<style>
    .producto-imagen { /* Estilo para las imágenes de producto */
        height: 200px; /* Altura fija para todas las imágenes */
        object-fit: contain; /* Ajuste de la imagen para contener el contenedor sin distorsión ni recorte */
    }
</style>
{% endblock %}